name: CI with Coveralls

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          check-latest: true

      - name: Verify Java & Maven version
        run: |
          java -version
          mvn -version

      - name: Build and test with Maven
        run: |
          mvn clean test jacoco:report coveralls:report \
            -DrepoToken=${COVERALLS_REPO_TOKEN}
